### PR TITLE
Add opus for mp4mux

### PR DESCRIPTION
**Pull request by hsnks100**
It supports opus for mp4mux.

### CODE REVIEW

**Comment by yapingcat** [comment]
missing read/write opus head  for opus codec

**Comment by yapingcat** [comment]
[0e25ecd](https://github.com/yapingcat/gomedia/commit/0e25ecd0de030e730795320b74325008cacf6fc4)

**Comment by yapingcat** [comment]
could you add some example code about read/write opus into mp4?

**Comment by hsnks100** [comment]
I want to write example code, but I'm worried about how to receive opus input.

Is there a good way?

**Pull request merged**
