### PR TITLE
mp4: use io.ReadSeeker & io.WriteSeeker

### PR DESCRIPTION
**Pull request by ydylla**
Hi @yapingcat,
thanks for this awesome lib.

Is there a specific reason why you did not use the `io.ReadSeeker` & `io.WriteSeeker` interfaces of the go standard library for the mp4 demuxer/muxer?
I think it would make the usage easier, since many things already implement these like `os.File` or `bytes.Buffer`.

This PR removes `mp4-io.go` and uses the above mentioned interfaces instead. 
It also renames the `Writetrailer` function of the muxer to `WriteTrailer` to be more consistent with the others.
Since this PR is a breaking change anyway, I thought this is also a good opportunity for the renaming.

I also have another question. Why are you using a go.mod file in any directory?
For me a single one in the root directory worked better (like [this](https://github.com/yapingcat/gomedia/commit/b9ff16c9ffade626c035f56571bde94c9caf8be3)). Especially when working with uncommitted changes in IntelliJ that uses code from multiple modules/directories.

### CODE REVIEW

**Comment by yapingcat** [comment]
thank you for your pr.
I've been very busy recently. Give me some time to check it. 

> I also have another question. Why are you using a go.mod file in any directory?

because I want to  release each package independently. maybe my idea is immature.
recently I've come to realize that this may not be the best way for Golang

**Comment by ydylla** [comment]
> I've been very busy recently. I need some time to check it.

No worries, its not urgent. For now, I will use my fork, so I am able to adapt things to my needs faster.

For example I also added auto-detection for aac sample rate & channel count: https://github.com/ydylla/gomedia/commit/0f561428da8eb703158d007d57d6b1e6e2d2aeab
I could also make a PR for that if you want.

Regarding the mod files, yes I think with go it is easier to just use one.
Otherwise you have to regularly update all mod files. For example the flv/go.mod file if anything in codec changes.
Also unused code/package are ignored by the compiler automatically.

**Comment by ydylla** [comment]
Awesome, thanks for the merge.

I see you also added mp4 in memory examples, do you think this is a common use case?
And sorry I actually did not notice that `bytes.Buffer` does not implement `io.Seek`, I just assumed it would.
But at least the in memory mp4 demux could be simplified to:
```go
b, _ := io.ReadAll(f)
crs := bytes.NewReader(b)
```
instead of implementing Read & Seek in the example.

**Comment by yapingcat** [comment]
> do you think this is a common use case?

That's not common use for mp4. 

> instead of implementing Read & Seek in the example.

thanks for reminding. I'll add some comments to remind others to use bytes.reader

**Pull request merged**
