### PR TITLE
added defaultCryptByteBlock, defaultSkipByteBlock, defaultConstantIV in tenc-box

### PR DESCRIPTION
**Pull request by iMro0t**

### CODE REVIEW

**Comment by yapingcat** [comment]
could you add some example ?  
please show us how to Encrypt/Decrypt MP4 file with cenc ,thank you

**Comment by iMro0t** [comment]
### HLS SAMPLE-AES CBCS Decryption

```go
package main

import (
	"bytes"
	"crypto/aes"
	"crypto/cipher"
	"encoding/hex"
	"github.com/yapingcat/gomedia/go-mp4"
	"io"
	"net/http"
	"os"
)

// demo to decrypt sample-aes cbcs
// source: https://demo.unified-streaming.com/k8s/features/no-handler-origin/multi-format-drm/master.m3u8
func main() {
	input := "https://demo.unified-streaming.com/k8s/features/no-handler-origin/multi-format-drm/tears-of-steel-avc1-1500k.cmfv"
	key, _ := hex.DecodeString("47943c25a4f1e6401184ff9c7fd4d806")

	req, _ := http.NewRequest(http.MethodGet, input, nil)
	req.Header.Set("Range", "bytes=0-52306") // init header + 1st segment
	resp, _ := http.DefaultClient.Do(req)
	b, _ := io.ReadAll(resp.Body)
	demuxer := mp4.CreateMp4Demuxer(bytes.NewReader(b))
	demuxer.ReadHead()
	demuxer.OnRawSample = func(cid mp4.MP4_CODEC_TYPE, sample []byte, subSample *mp4.SubSample) error {
		return decryptCbcs(sample, key, subSample)
	}

	f, _ := os.OpenFile("plain.mp4", os.O_CREATE|os.O_RDWR|os.O_TRUNC, 0755)
	muxer, _ := mp4.CreateMp4Muxer(f, mp4.WithMp4Flag(mp4.MP4_FLAG_FRAGMENT))
	vid := muxer.AddVideoTrack(mp4.MP4_CODEC_H264)

	for {
		pkg, err := demuxer.ReadPacket()
		if err != nil {
			break
		}
		muxer.Write(vid, pkg.Data, pkg.Pts, pkg.Dts)
	}
}

func decryptCbcs(sample []byte, key []byte, subSample *mp4.SubSample) (err error) {
	nrInCryptBlock := int(subSample.DefaultCryptByteBlock) * 16
	nrInSkipBlock := int(subSample.DefaultSkipByteBlock) * 16

	if len(subSample.Patterns) != 0 {
		var pos uint32 = 0
		for i := 0; i < len(subSample.Patterns); i++ {
			nrClear := uint32(subSample.Patterns[i].BytesClear)
			if nrClear > 0 {
				pos += nrClear
			}
			nrEnc := subSample.Patterns[i].BytesProtected
			if nrEnc > 0 {
				err = cbcsDecrypt(sample[pos:pos+nrEnc], key, subSample.IV[:], nrInCryptBlock, nrInSkipBlock)
				if err != nil {
					return err
				}
				pos += nrEnc
			}
		}
		return
	} else {
		err = cbcsDecrypt(sample, key, subSample.IV[:], nrInCryptBlock, nrInSkipBlock)
		if err != nil {
			return err
		}
	}
	return
}

// from http://github.com/Eyevinn/mp4ff
// cbcsCrypt does one in-place CBC encryption/decryption. Full if nrInSkipBlock == 0.
// The normal case is that nrInCryptBlock == 16 and nrInSkipBlock == 144.
func cbcsDecrypt(data []byte, key []byte, iv []byte, nrInCryptBlock, nrInSkipBlock int) error {
	pos := 0
	size := len(data) // This is the bytes that we should stripe decrypt
	aesCbcCrypto, err := aes.NewCipher(key)
	if err != nil {
		return err
	}
	cph := cipher.NewCBCDecrypter(aesCbcCrypto, iv)
	if nrInSkipBlock == 0 {
		nrToCrypt := size & ^0xf // Drops 4 last bits -> multiple of 16
		cph.CryptBlocks(data[:nrToCrypt], data[:nrToCrypt])
		return nil
	}
	for {
		if size-pos < nrInCryptBlock { // Leave the rest
			break
		}
		cph.CryptBlocks(data[pos:pos+nrInCryptBlock], data[pos:pos+nrInCryptBlock])
		pos += nrInCryptBlock
		if size-pos < nrInSkipBlock {
			break
		}
		pos += nrInSkipBlock
	}
	return nil
}

```

Similarly can be done for DASH fMP4 Widevine CENC

Credits: https://github.com/Eyevinn/mp4ff

**Comment by iMro0t** [comment]
@yapingcat

**Comment by yapingcat** [comment]
i will check and merge this pr in weekend

**Comment by 3052** [comment]
can we please have a CENC example also?

**Comment by 3052** [comment]
here is CENC example:

~~~go
package gomedia

import (
   "crypto/aes"
   "crypto/cipher"
   "github.com/yapingcat/gomedia/go-mp4"
)

// github.com/Eyevinn/mp4ff/blob/v0.40.2/mp4/crypto.go#L101
func DecryptCenc(sample []byte, key []byte, subSample *mp4.SubSample) error {
   block, err := aes.NewCipher(key)
   if err != nil {
      return err
   }
   stream := cipher.NewCTR(block, subSample.IV[:])
   if len(subSample.Patterns) != 0 {
      var pos uint32 = 0
      for j := 0; j < len(subSample.Patterns); j++ {
         ss := subSample.Patterns[j]
         nrClear := uint32(ss.BytesClear)
         if nrClear > 0 {
            pos += nrClear
         }
         nrEnc := ss.BytesProtected
         if nrEnc > 0 {
            stream.XORKeyStream(sample[pos:pos+nrEnc], sample[pos:pos+nrEnc])
            pos += nrEnc
         }
      }
   } else {
      stream.XORKeyStream(sample, sample)
   }
   return nil
}
~~~

**Comment by 3052** [comment]
https://github.com/yapingcat/gomedia/issues/113

**Pull request merged**
